### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sandydev29** [All4Gis/EquirectangularViewer#5]
Couldn't load plugin 'EquirectangularViewer' due to an error when calling its classFactory() method
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Sandesh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\EquirectangularViewer\__init__.py", line 13, in classFactory
    from .Geo360 import Geo360
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Sandesh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\EquirectangularViewer\Geo360.py", line 27, in <module>
    from EquirectangularViewer.Geo360Dialog import Geo360Dialog
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Sandesh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\EquirectangularViewer\Geo360Dialog.py", line 60, in <module>
    WindowUtils = cefpython .WindowUtils()
NameError: name 'cefpython' is not defined

```
EquirectangularViewer 1.2, QGIS 3.16.1-Hannover on Windows 7

**Comment by All4Gis** [comment]
You  need install `pip install cefpython3`
https://github.com/All4Gis/EquirectangularViewer#prerequisites
