### ISSUE TITLE
 module 'sys' has no attribute 'argv'

### ISSUE THREAD

**Issue by pankajsinghkalam** [All4Gis/EquirectangularViewer#7]
Traceback (most recent call last):
              File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\EquirectangularViewer\Geo360.py", line 123, in run
              self.StartCefPython()
              File "C:/Users/Lenovo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\EquirectangularViewer\Geo360.py", line 91, in StartCefPython
              cefpython.Initialize(settings)
              File "cefpython_py37.pyx", line 499, in cefpython_py37.Initialize
             AttributeError: module 'sys' has no attribute 'argv'

**Comment by All4Gis** [comment]
check this https://github.com/All4Gis/EquirectangularViewer/issues/4

**Comment by pankajsinghkalam** [comment]
Thank you now the viewer window is getting open.
But the images is not visible and i am getting a message "There is no associated image"

**Comment by All4Gis** [comment]
are you using the example project? remember that you have to put the path of your image, check the project example https://github.com/All4Gis/EquirectangularViewer/tree/master/code/Project_example

**Comment by pankajsinghkalam** [comment]
yes
now, it is showing a message "There is no superiority that follows"
